### ISSUE TITLE
SelectDate event missing

### ISSUE THREAD

**Issue by StephanBeutel** [David-Mulder/paper-date-picker#4]
It would be great if the date selection would fire an event to react on.

**Comment by David-Mulder** [comment]
Are you talking about the date picker dialog as a whole, or just the date picker itself? Second sounds reasonable, but just want to check :) .

**Comment by StephanBeutel** [comment]
The Dialog

Mit freundlichen Grüßen
Best regards

Stephan Beutel

**Comment by David-Mulder** [comment]
Added a `value-changed` (when the OK button is clicked) and `selection-changed` (whenever the date selection is changed) event. And just to check: if you're actually making a polymer app you can use direct property bindings for this: https://www.polymer-project.org/articles/communication.html (that's what I was doing, so I didn't notice the problem).

Either way, running a `bower update` should pull the new version, if there's any problem with it you can reopen this issue.

**Comment by StephanBeutel** [comment]
Thanks a lot. That works perfect.

2015-01-25 15:41 GMT+01:00 David Mulder <notifications@github.com>:
